  name: Slip-Kerala

  on:
    work_flow_dispatch:
    schedule:
      - cron: '15 0-23 1-31 1-12 0-6'
  
  jobs:

    build:

      runs-on: ubuntu-latest

      steps:
        -id: repo
         name: Slip-Kerala
         uses: actions/checkout@v2

        -id: python
         name: Python Setup and Packages Installation
         uses: actions/setup-python@v2
         with:
           python-version: '3.9'
           cache: 'pip'
        -run: pip install -r requirements.txt

        -id: jupyter
         name: Jupyter Notebook Execution
         run: jupyter execute  slip-k.ipynb
         shell: bash
